name: FastAPI CI/CD
on:
  push:
    branches:
      - main
      - dev
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sksat/setup-rye@v0.22.0
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
      - name: Sync Rye
        run: rye sync
      - name: Run Pytest
        run: rye run python -m pytest
      - name: Run uvicorn
        run: |- 
          cd src
          nohup rye run uvicorn main:app --host=0.0.0.0 --port=8000 > uvicorn.log 2>&1 & echo $! > ../uvicorn_pid.txt
      - name: Run locust
        run: rye run locust --host=http://0.0.0.0:8000 --headless -u 1 --run-time 10
      - name: ls
        run: ls -la
      - name: Shutdown uvicorn
        run: kill -9 `cat uvicorn_pid.txt`