name: FastAPI CI/CD
on:
  push:
    branches:
      - main
      - dev
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sksat/setup-rye@v0.22.0
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
      - name: Sync Rye
        run: rye sync
      - name: Run Pytest
        run: rye run python -m pytest
      - name: Run uvicorn
        run: rye run uvicorn main:app --reload
      - name: Run locust
        run: rye run locust --host=http://127.0.0.1:8000 --headless -u 5 --run-time 60